### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by JaakkoLipsanen** [javaLabra/Javalabra2016-2#1]
edit: jaha, ei pitäny kyllä tänne mennä

**Comment by JaakkoLipsanen** [comment]
Jaha ei pitäny mennä tänne :D

**Comment by Ilpolainen** [comment]
Hyvä palaute silti. . :)

2016-11-20 3:01 GMT+02:00 Jaakko Lipsanen notifications@github.com:
